### ISSUE TITLE
[Request] Add hdoc support

### ISSUE THREAD

**Issue by paulocoutinhox** [raygerlabs/templatepp#14]
Hi,

Can you add hdoc?

https://hdoc.io/

Thanks.

**Comment by raygerlabs** [comment]
Hi,

I never used hdoc before. Is it like Doxygen?

Regards

**Comment by raygerlabs** [comment]
https://docs.hdoc.io/raygerlabs/templatepp/
I have an issue however, because of SDL2. During compilation of the API doc, the doc generation tool reports the following:
```
[2022-06-11 20:59:54.948] [info] [1/1] processing /home/raygerlabs/workspace/templatepp/src/application.cpp
In file included from /home/raygerlabs/workspace/templatepp/src/application.cpp:2:
In file included from /home/raygerlabs/workspace/templatepp/include/templatepp/application.hpp:5:
In file included from /home/raygerlabs/workspace/templatepp/include/templatepp/sdl_utils.hpp:7:
In file included from /home/raygerlabs/.conan/data/sdl/2.0.20/_/_/package/5881fd4aa0068ca215365c1213037baf61c83c43/include/SDL2/SDL.h:38:
In file included from /home/raygerlabs/.conan/data/sdl/2.0.20/_/_/package/5881fd4aa0068ca215365c1213037baf61c83c43/include/SDL2/SDL_cpuinfo.h:102:
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/include/immintrin.h:29:
/usr/lib/gcc/x86_64-linux-gnu/9/include/xmmintrin.h:54:3: fatal error: argument to '__builtin_prefetch' must be a constant integer
  __builtin_prefetch (__P, (__I & 0x4) >> 2, __I & 0x3);
  ^                        ~~~~~~~~~~~~~~~~
1 error generated.
Error while processing /home/raygerlabs/workspace/templatepp/src/application.cpp.
[2022-06-11 20:59:55.722] [error] Failed to parse source file: /home/raygerlabs/workspace/templatepp/src/application.cpp
```

I am still investigating what is the issue. It seems intrinsic function is not found which is weird, because the application builds fine.

**Comment by raygerlabs** [comment]
GCC is not supported by hdoc, only clang is. It seems this is the root cause of the compilation error reported by hdoc.

Configuration file is provided but conan doesn't provide hdoc. You must install this tool manually on your PC to get it working.

It seems fancy, but it cannot be automated like Doxygen for example.

**Comment by paulocoutinhox** [comment]
No problem. You can close without it. It is not a requirement. And if it is only for a specific compiler, dont make sense.
